CREATE TABLE prouni (
	id SERIAL primary key,
  	ANO_CONCESSAO_BOLSA INT,
  	CODIGO_EMEC_IES_BOLSA INT,
  	NOME_IES_BOLSA VARCHAR(255),
  	TIPO_BOLSA VARCHAR(255),
  	MODALIDADE_ENSINO_BOLSA VARCHAR(255),
  	NOME_CURSO_BOLSA VARCHAR(255),
  	NOME_TURNO_CURSO_BOLSA VARCHAR(255),
  	CPF_BENEFICIARIO_BOLSA VARCHAR(255),
  	SEXO_BENEFICIARIO_BOLSA CHAR(1),
  	RACA_BENEFICIARIO_BOLSA VARCHAR(255),
  	DT_NASCIMENTO_BENEFICIARIO DATE,
  	BENEFICIARIO_DEFICIENTE_FISICO VARCHAR(3),
  	REGIAO_BENEFICIARIO_BOLSA VARCHAR(255),
  	SIGLA_UF_BENEFICIARIO_BOLSA CHAR(2),
  	MUNICIPIO_BENEFICIARIO_BOLSA VARCHAR(255),
  	idade FLOAT
);

COPY prouni (
  	ANO_CONCESSAO_BOLSA,
	CODIGO_EMEC_IES_BOLSA,
  	NOME_IES_BOLSA,
  	TIPO_BOLSA,
  	MODALIDADE_ENSINO_BOLSA,
  	NOME_CURSO_BOLSA,
  	NOME_TURNO_CURSO_BOLSA,
  	CPF_BENEFICIARIO_BOLSA,
  	SEXO_BENEFICIARIO_BOLSA,
  	RACA_BENEFICIARIO_BOLSA,
  	DT_NASCIMENTO_BENEFICIARIO,
  	BENEFICIARIO_DEFICIENTE_FISICO,
  	REGIAO_BENEFICIARIO_BOLSA,
  	SIGLA_UF_BENEFICIARIO_BOLSA,
  	MUNICIPIO_BENEFICIARIO_BOLSA,
  	idade
) 
FROM 'c:\prouni.csv' DELIMITER ',' CSV HEADER;
