CREATE TABLE curso(
  	id SERIAL primary key,
  	NOME_CURSO_BOLSA VARCHAR(255),
  	NOME_TURNO_CURSO_BOLSA VARCHAR(255),
    	FOREIGN KEY (id_aluno) REFERENCES pessoa (id)
);

INSERT INTO curso (NOME_CURSO_BOLSA, NOME_TURNO_CURSO_BOLSA, id_aluno)
SELECT NOME_CURSO_BOLSA, NOME_TURNO_CURSO_BOLSA, id
FROM prouni;